name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install PortAudio
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev
        
    - name: Download dependencies
      run: go mod download
      
    - name: Run lint
      run: make lint
      
    - name: Build binaries
      run: make build
      
    - name: Run tests
      run: make test
